### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by vinctux** [vinctux/themeon#1]
Instead of keeping a `TODO.md` in repo, I'll reserve this first issue for listing up things that should be done in future. Suggestions should be opened as a separate issue, for the discussion, then referenced here.

## WIP

- [ ] Support for non-`apt` package managers.
- [ ] Fix local mode (for installing from disk).

## Later

- [ ] Separate `README.md` into a standard user documentation and developer documentation.
